#Bluetooth address of the Smart Trainer
bluetooth:
  address: #DF:36:42:3D:BD:A4
  uuid: 00002a63-0000-1000-8000-00805f9b34fb

# settings for the LED strip
led_strip:
  brightness: 100
  channel: 0
  count: 247
  dma: 10
  freq_hz: 800000

  invert: false
  max_brightness: 255
  pin: 18

# settings for the Power2Color modes.
mode_params:
  idle_color: [255, 0, 0] #255,0,0 is white.
  initial_brightness_duration: 2 
  initial_brightness_value: 100
  running_length: 10  # length in leds of the running light in idle mode
  slowdown_speed_factor: 10  # default speed is high. I prefer 10. you can slow it further by teting values > 10 up to 100
  running_brightness: 100  # brightness of the running light in idle mode
  running_fade_length: 30  # fade the running light in idle mode

# settings if the intervals are based on power zones from the athlete profile on intervals.icu
use_zones_from_intervals_icu: false
# settings to access the interfal.icu API
athlete:
  id: your_id_goes_here                  #place your intervals.icu athlete id here webpage -> profile 
  api_key: your_key_goes_here          #place your intervals.icu api key here webpage -> profile -> api key -> view
  ftp_type: indoor_ftp            #select whicht power zone definitions shall be used defaults are ftp, indoor_ftp


#alternate, local power zone deifinitions if not using intervals.icu
power_zones:
- name: Zone 1
  min_watt: 0
  max_watt: 132
- name: Zone 2
  min_watt: 133
  max_watt: 176
- name: Zone 3
  min_watt: 177
  max_watt: 211
- name: Zone 4
  min_watt: 212
  max_watt: 246
- name: Zone 5
  min_watt: 247
  max_watt: .inf

# colors for the zones. must be the same or more than the number of zones
power_zones_colors:
- [0, 0, 255]       # Z1: Blue
- [0, 255, 0]       # Z2: Green
- [255, 255, 0]     # Z3: Yellow
- [255, 165, 0]     # Z4: range
- [255, 0, 0]       # Z5: Red
- [255, 0, 255]     # Z6: Magenta
- [128, 0, 128]     # Z7: Purple
- [0, 128, 128]     # Z8: Teal
- [128, 128, 0]     # Z9: Olive
